name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            # - name: Install Cowsay Program
            #   run: sudo apt-get install cowsay -y
              
            # - name: Execute Cowsay CMD
            #   run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt

            # - name: Test File Exists
            #   run: grep -i "dragon" dragon.txt

            # - name: Read File
            #   run: cat dragon.txt

            - name: List Repo Files
              run: ls -lrta

            - name: Run Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

            - name: Upload dragon.txt
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    second_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
           - name: Step1 
             run: echo "This is the second job"
           - name: Download dragon.txt
             uses: actions/download-artifact@v4
             with:
               name: dragon-text-file
           - name: Test file exists
             run: grep -i "dragon" dragon.txt

    third_job:
        runs-on: ubuntu-latest
        needs: [first_job,second_job]
        steps:
           - name: Step1 
             run: echo "This is the third job"